node {

    withMaven(maven:'Maven 3.6.0') {

        stage('Build') {
            dir (../) {
                sh 'mvn clean package -Dmaven.test.skip=true'

                def pom = readMavenPom file:'pom.xml'
                print pom.version
                env.version = pom.version
            }

        }

        stage('Image') {
            dir ('apache') {
                def app = docker.build "bondblaze/microservice-kubernetes-demo-apache:${env.version}"
                app.push()
            }
        }
    }
}